services:
  mlflow:
    image: python:3.11-slim
    working_dir: /app
    command: >
      sh -lc "
      pip install mlflow==3.3.0 &&
      mlflow server
        --backend-store-uri sqlite:////app/mlflow.db
        --serve-artifacts
        --artifacts-destination /app/mlruns
        --host 0.0.0.0
        --port 5000
      "
    ports: ["5000:5000"]
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db

  api:
    image: xgb-churn:cpu        # build once: docker build -t xgb-churn:cpu .
    environment:
      - MODEL_URI=models:/xgb_churn/Production
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on: [mlflow]
    ports: ["18080:8080"]
